project:
  type: book
  output-dir: docs

book:
  title: "T2D: Exercise and Genetic Expression Profile"
  subtitle: Program
  author: "Francois Collin, Ph.D."
  page-footer: "Copyright 2022, FCA Collin, Ph.D."
  chapters:
    - index.qmd
    - intro.qmd
    - t2d_01_dmg.qmd
    - t2d_02_dmg.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: litera
    page-layout: full
    code-fold: show
    code-overflow: wrap
    code-summary: "Show the code"
  pdf:
    documentclass: scrreport
    header-includes: |
      \usepackage{makeidx}
      \makeindex
    include-after: |
      \printindex

editor: visual
